
GET http://localhost:3004/api/blogs

###

POST http://localhost:3004/api/blogs
Content-Type: application/json

{
    "title": "x Post",
    "author": "Janis Chaplin",
    "url": "http://localhost:4040",
    "likes": "2"
}